project_id = "nyvtpamnbsadltuctxwz"

[functions.generate-course]
verify_jwt = false

[functions.lesson-chat]
verify_jwt = false

[functions.generate-exercises]
verify_jwt = false

[functions.grade-exercise]
verify_jwt = false
